name = "dwtc-staging-event-cron"
main = "src/index.ts"
compatibility_date = "2024-01-07"

[triggers]
crons = ["0 9 * * *"]


[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true